name: elbdesk_app
description: "ElbDesk"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  hooks_riverpod: 2.6.1
  flutter_hooks: 0.20.5
  riverpod_annotation: 2.6.1
  cupertino_icons: 1.0.6
  go_router: 14.1.4
  uuid: 4.5.1
  intl: 0.20.2
  flutter_single_instance: 1.2.3
  windows_taskbar: 1.1.2


  serverpod_auth_client: 2.9.1
  serverpod_auth_shared_flutter: 2.9.1
  serverpod_flutter: 2.9.1
  serverpod_auth_email_flutter: 2.9.1
  csv: ^6.0.0
  app_links: 6.4.0
  crypto: 3.0.6


  elbdesk_client:
  elbdesk_ui:
  elbdesk_core:
  elbdesk_prepress:
  elbdesk_crm:
  elbdesk_sales:
  project_core:
  elbdesk_window_manager:
  elbdesk_platform_info:

dependency_overrides:
  collection: 1.19.1

dev_dependencies:
  elbdesk_lints:
  freezed: 2.5.8
  json_serializable: 6.9.3
  riverpod_generator: 2.6.4
  go_router_builder: 2.7.3
  build_runner: 2.4.14
  flutter_launcher_icons: 0.14.3
  msix: 3.16.8

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Black.ttf
          weight: 900

  assets:
    - assets/temp/
    - assets/settings/
    - assets/icons/
    - assets/img/
    - assets/img/taskbar_badges/


# min_version: 0.1.0.0
  # logo_path: assets/icons/coe_logo_1024.png
  # logo_path: windows/runner/resources/app_icon_test.ico
  # windows_build_args: --dart-define=RUN_MODE=test --release
  # windows_build_args: --dart-define=RUN_MODE=prod --release

# fvm dart run msix:create
# 
#   # display_name: ElbDesk
#   execution_alias: elbdesk
#   publisher_display_name: App Ahoi GmbH
#   # identity_name: cloud.elbdesk.test
#   # msix_version: 0.1.0.1
#   certificate_path: ..\..\.certificates\AppAhoiGmbH.pfx
#   certificate_password: g%=gwAVP0u2fS?.o@>vM

# 
#   display_name: ElbDesk
#   publisher_display_name: App Ahoi GmbH
#   identity_name: cloud.elbdesk.test
#   msix_version: 0.1.0.2
#   execution_alias: elbdesk
