arb-dir: lib/l10n
template-arb-file: elb_prepress_l10n_en.arb
output-localization-file: elb_prepress_localizations.dart
output-class: ElbPrepressLocalizations
synthetic-package: false
output-dir: lib/l10n
nullable-getter: false