name: elbdesk_prepress
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.3"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  freezed_annotation: 2.4.4
  hooks_riverpod: 2.6.1
  json_annotation: 4.9.0
  riverpod_annotation: 2.6.1
  collection: 1.19.1

  # for color import
  file_selector: 1.0.3
  csv: 6.0.0
  xml: 6.5.0

  # for pdf upload and ae pilot
  # pdfx: ^2.9.2
  http: 1.2.2
  path: 1.9.1
  path_provider: 2.1.5
  file_picker: 8.1.7
  url_launcher: 6.3.0
  archive: ^4.0.7

  desktop_drop:
    git:
      url: https://github.com/App-Ahoi/flutter-plugins.git
      path: packages/desktop_drop
      ref: 243be7638de6245071e565e5a81935d73dda5bca 


  elbdesk_client:
  elbdesk_ui:
  elbdesk_core:
  elbdesk_crm:
  elbdesk_sales:
  project_core:
  elbdesk_platform_info:
  elbdesk_window_manager:
  elbdesk_backend_core_client:
    path: ../../servers/elbdesk_backend_core/elbdesk_backend_core_client

dev_dependencies:
  elbdesk_lints:
  freezed: 2.5.8
  json_serializable: 6.9.3
  riverpod_generator: 2.6.4
  build_runner: 2.4.14


flutter:
  generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
