name: "Create & Push Force Migration"
description: "Creates a force migration, commits and pushes it to the repository."

inputs:
  server_path:
    description: "Path to the server"
    required: true
  branch:
    description: "Branch to push to"
    required: true

runs:
  using: "composite"
  steps:

    ############################################################
    # 1. Create force migration
    ############################################################
    - name: Create force migration
      shell: bash
      working-directory: ${{ inputs.server_path }}
      run: |
        serverpod create-migration --force
        echo "::notice::Force migrations created."


    ############################################################
    # 2. Commit and push force migrations
    ############################################################
    - name: Commit & Push force migrations
      uses: ./.github/actions/commit-push-migrations
      with:
        server_path: ${{ inputs.server_path }}
        branch: ${{ inputs.branch }}