name: elbdesk_ui
description: "A new Flutter package project."
version: 0.0.1
homepage: appahoi.com
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.3"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  riverpod_annotation: 2.6.1
  flutter_hooks: 0.20.5
  hooks_riverpod: 2.6.1
  auto_size_text: 3.0.0
  collection: 1.19.1

  uuid: 4.5.1
  flutter_svg: 2.0.10+1
  shimmer: 3.0.0
  cached_network_image: 3.4.1

  elbdesk_core:
  
  elbdesk_window_manager:
  elbdesk_platform_info:
  elbdesk_backend_core_client:
    path: ../../servers/elbdesk_backend_core/elbdesk_backend_core_client
    



  desktop_drop:
    git:
      url: https://github.com/App-Ahoi/flutter-plugins.git
      path: packages/desktop_drop
      ref: 243be7638de6245071e565e5a81935d73dda5bca 

dev_dependencies:
  elbdesk_lints:
  riverpod_generator: 2.6.4
  build_runner: 2.4.14