arb-dir: lib/l10n
template-arb-file: elb_crm_l10n_en.arb
output-localization-file: elb_crm_localizations.dart
output-class: ElbCrmLocalizations
synthetic-package: false
output-dir: lib/l10n
nullable-getter: false