import 'package:elbdesk_client/elbdesk_client.dart';
import 'package:elbdesk_core/elbdesk_core.dart';
import 'package:elbdesk_crm/src/country_code/models/country_code.dart';

final List<CountryCode> allCountryCodesForSetup = [
  CountryCode(
    code: 'AD',
    name: 'Andorra',
    isoCode: 'AD',
    numericIsoCode: 20,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'AE',
    name: 'Vereinigte Arabische Emirate',
    isoCode: 'AE',
    numericIsoCode: 784,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'AL',
    name: 'Albanien',
    isoCode: 'AL',
    numericIsoCode: 8,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'AM',
    name: 'Armenien',
    isoCode: 'AM',
    numericIsoCode: 51,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'AO',
    name: 'Angola',
    isoCode: 'AO',
    numericIsoCode: 24,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'AR',
    name: 'Argentinien',
    isoCode: 'AR',
    numericIsoCode: 32,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'AT',
    name: 'Österreich',
    isoCode: 'AT',
    numericIsoCode: 40,
    addressFormat: CountryCodeAddressFormat.blank_postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'AT',
    intrastatCode: 'AT',
    taxScheme: '0007',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'AU',
    name: 'Australien',
    isoCode: 'AU',
    numericIsoCode: 36,
    addressFormat: CountryCodeAddressFormat.city_country_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: true,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'AZ',
    name: 'Aserbaidschan',
    isoCode: 'AZ',
    numericIsoCode: 31,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BA',
    name: 'Bosnien und Herzegowina',
    isoCode: 'BA',
    numericIsoCode: 70,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BD',
    name: 'Bangladesch',
    isoCode: 'BD',
    numericIsoCode: 50,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BE',
    name: 'Belgien',
    isoCode: 'BE',
    numericIsoCode: 56,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'BE',
    intrastatCode: 'BE',
    taxScheme: '9925',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BG',
    name: 'Bulgarien',
    isoCode: 'BG',
    numericIsoCode: 100,
    addressFormat: CountryCodeAddressFormat.city_country_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'BG',
    intrastatCode: 'BG',
    taxScheme: '9926',
    showState: true,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BH',
    name: 'Bahrain',
    isoCode: 'BH',
    numericIsoCode: 48,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BM',
    name: 'Bermuda',
    isoCode: 'BM',
    numericIsoCode: 60,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BN',
    name: 'Brunei Darussalam',
    isoCode: 'BN',
    numericIsoCode: 96,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BO',
    name: 'Bolivien',
    isoCode: 'BO',
    numericIsoCode: 68,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BR',
    name: 'Brasilien',
    isoCode: 'BR',
    numericIsoCode: 76,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BS',
    name: 'Bahamas',
    isoCode: 'BS',
    numericIsoCode: 44,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'BW',
    name: 'Botsuana',
    isoCode: 'BW',
    numericIsoCode: 72,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CA',
    name: 'Kanada',
    isoCode: 'CA',
    numericIsoCode: 124,
    addressFormat: CountryCodeAddressFormat.city_country_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    federalRegion: 'Provinz',
    showState: true,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CH',
    name: 'Schweiz',
    isoCode: 'CH',
    numericIsoCode: 756,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CL',
    name: 'Chile',
    isoCode: 'CL',
    numericIsoCode: 152,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CM',
    name: 'Kamerun',
    isoCode: 'CM',
    numericIsoCode: 120,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CN',
    name: 'China',
    isoCode: 'CN',
    numericIsoCode: 156,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CO',
    name: 'Kolumbien',
    isoCode: 'CO',
    numericIsoCode: 170,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CR',
    name: 'Costa Rica',
    isoCode: 'CR',
    numericIsoCode: 188,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.first,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CY',
    name: 'Zypern',
    isoCode: 'CY',
    numericIsoCode: 196,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'CY',
    intrastatCode: 'CY',
    taxScheme: '9928',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'CZ',
    name: 'Tschechien',
    isoCode: 'CZ',
    numericIsoCode: 203,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'CZ',
    intrastatCode: 'CZ',
    taxScheme: '9929',
    showState: true,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'DE',
    name: 'Deutschland',
    isoCode: 'DE',
    numericIsoCode: 276,
    addressFormat: CountryCodeAddressFormat.blank_postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'DE',
    intrastatCode: 'DE',
    taxScheme: '9930',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'DK',
    name: 'Dänemark',
    isoCode: 'DK',
    numericIsoCode: 208,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'DK',
    intrastatCode: 'DK',
    taxScheme: '0184',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'DO',
    name: 'Dominikanische Republik',
    isoCode: 'DO',
    numericIsoCode: 214,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'DZ',
    name: 'Algerien',
    isoCode: 'DZ',
    numericIsoCode: 12,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'EC',
    name: 'Ecuador',
    isoCode: 'EC',
    numericIsoCode: 218,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'EE',
    name: 'Estland',
    isoCode: 'EE',
    numericIsoCode: 233,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'EE',
    intrastatCode: 'EE',
    taxScheme: '9931',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'EG',
    name: 'Ägypten',
    isoCode: 'EG',
    numericIsoCode: 818,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'EL',
    name: 'Griechenland',
    isoCode: 'EL',
    numericIsoCode: 300,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'EL',
    intrastatCode: 'EL',
    taxScheme: '0097',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'ES',
    name: 'Spanien',
    isoCode: 'ES',
    numericIsoCode: 724,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'ES',
    intrastatCode: 'ES',
    taxScheme: '9920',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'ET',
    name: 'Äthiopien',
    isoCode: 'ET',
    numericIsoCode: 231,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'FI',
    name: 'Finnland',
    isoCode: 'FI',
    numericIsoCode: 246,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'FI',
    intrastatCode: 'FI',
    taxScheme: '9910',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'FJ',
    name: 'Fidschiinseln',
    isoCode: 'FJ',
    numericIsoCode: 242,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'FO',
    name: 'Färöer',
    isoCode: 'FO',
    numericIsoCode: 234,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'FR',
    name: 'Frankreich',
    isoCode: 'FR',
    numericIsoCode: 250,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'FR',
    intrastatCode: 'FR',
    taxScheme: '0009',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'GB',
    name: 'Großbritannien',
    isoCode: 'GB',
    numericIsoCode: 826,
    addressFormat: CountryCodeAddressFormat.city_country_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    intrastatCode: 'GB',
    taxScheme: '9932',
    showState: true,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'GE',
    name: 'Georgien',
    isoCode: 'GE',
    numericIsoCode: 268,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'GG',
    name: 'Guernsey',
    isoCode: 'GG',
    numericIsoCode: 831,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'GH',
    name: 'Ghana',
    isoCode: 'GH',
    numericIsoCode: 288,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'GL',
    name: 'Grönland',
    isoCode: 'GL',
    numericIsoCode: 304,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'GT',
    name: 'Guatemala',
    isoCode: 'GT',
    numericIsoCode: 320,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'HK',
    name: 'Hongkong (SAR)',
    isoCode: 'HK',
    numericIsoCode: 344,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'HN',
    name: 'Honduras',
    isoCode: 'HN',
    numericIsoCode: 340,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'HR',
    name: 'Kroatien',
    isoCode: 'HR',
    numericIsoCode: 191,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'HR',
    intrastatCode: 'HR',
    taxScheme: '9934',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'HU',
    name: 'Ungarn',
    isoCode: 'HU',
    numericIsoCode: 348,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'HU',
    intrastatCode: 'HU',
    taxScheme: '9910',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'ID',
    name: 'Indonesien',
    isoCode: 'ID',
    numericIsoCode: 360,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'IE',
    name: 'Irland',
    isoCode: 'IE',
    numericIsoCode: 372,
    addressFormat: CountryCodeAddressFormat.city_country_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'IE',
    intrastatCode: 'IE',
    taxScheme: '9935',
    showState: true,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'IL',
    name: 'Israel',
    isoCode: 'IL',
    numericIsoCode: 376,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'IM',
    name: 'Isle of Man',
    isoCode: 'IM',
    numericIsoCode: 833,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'IN',
    name: 'Indien',
    isoCode: 'IN',
    numericIsoCode: 356,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'IS',
    name: 'Island',
    isoCode: 'IS',
    numericIsoCode: 352,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'IT',
    name: 'Italien',
    isoCode: 'IT',
    numericIsoCode: 380,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'IT',
    intrastatCode: 'IT',
    taxScheme: '0097',
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'JE',
    name: 'Jersey',
    isoCode: 'JE',
    numericIsoCode: 832,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'JM',
    name: 'Jamaika',
    isoCode: 'JM',
    numericIsoCode: 388,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'JO',
    name: 'Jordanien',
    isoCode: 'JO',
    numericIsoCode: 400,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'JP',
    name: 'Japan',
    isoCode: 'JP',
    numericIsoCode: 392,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'KE',
    name: 'Kenia',
    isoCode: 'KE',
    numericIsoCode: 404,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    code: 'KH',
    name: 'Kambodscha',
    isoCode: 'KH',
    numericIsoCode: 116,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'KR',
    name: 'Südkorea',
    isoCode: 'KR',
    numericIsoCode: 410,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'KW',
    name: 'Kuwait',
    isoCode: 'KW',
    numericIsoCode: 414,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'KY',
    name: 'Kaimaninseln',
    isoCode: 'KY',
    numericIsoCode: 136,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'KZ',
    name: 'Kasachstan',
    isoCode: 'KZ',
    numericIsoCode: 398,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'LB',
    name: 'Libanon',
    isoCode: 'LB',
    numericIsoCode: 422,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'LI',
    name: 'Liechtenstein',
    isoCode: 'LI',
    numericIsoCode: 438,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'LK',
    name: 'Sri Lanka',
    isoCode: 'LK',
    numericIsoCode: 144,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'LT',
    name: 'Litauen',
    isoCode: 'LT',
    numericIsoCode: 440,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'LT',
    intrastatCode: 'LT',
    taxScheme: '0200',
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'LU',
    name: 'Luxemburg',
    isoCode: 'LU',
    numericIsoCode: 442,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'LU',
    intrastatCode: 'LU',
    taxScheme: '9938',
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'LV',
    name: 'Lettland',
    isoCode: 'LV',
    numericIsoCode: 428,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'LV',
    intrastatCode: 'LV',
    taxScheme: '9939',
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MA',
    name: 'Marokko',
    isoCode: 'MA',
    numericIsoCode: 504,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MC',
    name: 'Monaco',
    isoCode: 'MC',
    numericIsoCode: 492,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'ME',
    name: 'Montenegro',
    isoCode: 'ME',
    numericIsoCode: 499,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MG',
    name: 'Madagaskar',
    isoCode: 'MG',
    numericIsoCode: 450,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MK',
    name: 'Nordmazedonien',
    isoCode: 'MK',
    numericIsoCode: 807,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MN',
    name: 'Mongolei',
    isoCode: 'MN',
    numericIsoCode: 496,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MO',
    name: 'Macau (SAR)',
    isoCode: 'MO',
    numericIsoCode: 446,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MT',
    name: 'Malta',
    isoCode: 'MT',
    numericIsoCode: 470,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'MT',
    intrastatCode: 'MT',
    taxScheme: '9943',
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MU',
    name: 'Mauritius',
    isoCode: 'MU',
    numericIsoCode: 480,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MV',
    name: 'Malediven',
    isoCode: 'MV',
    numericIsoCode: 462,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MW',
    name: 'Malawi',
    isoCode: 'MW',
    numericIsoCode: 454,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MX',
    name: 'Mexiko',
    isoCode: 'MX',
    numericIsoCode: 484,
    addressFormat: CountryCodeAddressFormat.city_country_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: true,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MY',
    name: 'Malaysia',
    isoCode: 'MY',
    numericIsoCode: 458,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'MZ',
    name: 'Mosambik',
    isoCode: 'MZ',
    numericIsoCode: 508,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'NA',
    name: 'Namibia',
    isoCode: 'NA',
    numericIsoCode: 516,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'NG',
    name: 'Nigeria',
    isoCode: 'NG',
    numericIsoCode: 566,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'NI',
    name: 'Nordirland',
    isoCode: 'GBN',
    numericIsoCode: 826,
    addressFormat: CountryCodeAddressFormat.city_country_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    intrastatCode: 'GBN',
    taxScheme: '9932',
    showState: true,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'NL',
    name: 'Niederlande',
    isoCode: 'NL',
    numericIsoCode: 528,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'NL',
    intrastatCode: 'NL',
    taxScheme: '9944',
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'NO',
    name: 'Norwegen',
    isoCode: 'NO',
    numericIsoCode: 578,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
  ),
  CountryCode(
    isPrimary: false,
    code: 'NP',
    name: 'Nepal',
    isoCode: 'NP',
    numericIsoCode: 524,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'NZ',
    name: 'Neuseeland',
    isoCode: 'NZ',
    numericIsoCode: 554,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'OM',
    name: 'Oman',
    isoCode: 'OM',
    numericIsoCode: 512,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'PA',
    name: 'Panama',
    isoCode: 'PA',
    numericIsoCode: 591,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    isPrimary: false,
    code: 'PE',
    name: 'Peru',
    isoCode: 'PE',
    numericIsoCode: 604,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    meta: DataMeta.initial(),
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'PH',
    name: 'Philippinen',
    isoCode: 'PH',
    numericIsoCode: 608,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'PK',
    isPrimary: false,
    name: 'Pakistan',
    isoCode: 'PK',
    numericIsoCode: 586,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'PL',
    name: 'Polen',
    isoCode: 'PL',
    numericIsoCode: 616,
    isPrimary: false,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'PL',
    intrastatCode: 'PL',
    taxScheme: '9945',
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'PR',
    name: 'Puerto Rico',
    isPrimary: false,
    isoCode: 'PR',
    numericIsoCode: 630,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'PT',
    name: 'Portugal',
    isPrimary: false,
    isoCode: 'PT',
    numericIsoCode: 620,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'PT',
    intrastatCode: 'PT',
    taxScheme: '9946',
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'PY',
    isPrimary: false,
    name: 'Paraguay',
    isoCode: 'PY',
    numericIsoCode: 600,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    isPrimary: false,
    code: 'QA',
    name: 'Katar',
    isoCode: 'QA',
    numericIsoCode: 634,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'RO',
    name: 'Rumänien',
    isoCode: 'RO',
    numericIsoCode: 642,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'RO',
    isPrimary: false,
    intrastatCode: 'RO',
    taxScheme: '9947',
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'RS',
    name: 'Serbien',
    isoCode: 'RS',
    numericIsoCode: 688,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
    isPrimary: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'RU',
    name: 'Russland',
    isPrimary: false,
    isoCode: 'RU',
    numericIsoCode: 643,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'SA',
    name: 'Saudi-Arabien',
    isoCode: 'SA',
    numericIsoCode: 682,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    isPrimary: false,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'SE',
    name: 'Schweden',
    isPrimary: false,
    isoCode: 'SE',
    numericIsoCode: 752,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'SE',
    intrastatCode: 'SE',
    taxScheme: '9948',
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    isPrimary: false,
    code: 'SG',
    name: 'Singapur',
    isoCode: 'SG',
    numericIsoCode: 702,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'SI',
    name: 'Slowenien',
    isoCode: 'SI',
    numericIsoCode: 705,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    isPrimary: false,
    euCode: 'SI',
    intrastatCode: 'SI',
    taxScheme: '9950',
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'SK',
    name: 'Slowakei',
    isPrimary: false,
    isoCode: 'SK',
    numericIsoCode: 703,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    euCode: 'SK',
    intrastatCode: 'SK',
    taxScheme: '9951',
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'TH',
    name: 'Thailand',
    isPrimary: false,
    isoCode: 'TH',
    numericIsoCode: 764,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'TN',
    isPrimary: false,
    name: 'Tunesien',
    isoCode: 'TN',
    numericIsoCode: 788,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'TR',
    name: 'Türkei',
    isoCode: 'TR',
    numericIsoCode: 792,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    isPrimary: false,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'UA',
    name: 'Ukraine',
    isoCode: 'UA',
    numericIsoCode: 804,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    isPrimary: false,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    isPrimary: false,
    meta: DataMeta.initial(),
    code: 'US',
    name: 'Vereinigte Staaten',
    isoCode: 'US',
    numericIsoCode: 840,
    addressFormat: CountryCodeAddressFormat.city_country_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: true,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'UY',
    isPrimary: false,
    name: 'Uruguay',
    isoCode: 'UY',
    numericIsoCode: 858,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'UZ',
    isPrimary: false,
    name: 'Usbekistan',
    isoCode: 'UZ',
    numericIsoCode: 860,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    isPrimary: false,
    meta: DataMeta.initial(),
    code: 'VA',
    name: 'Vatikanstadt',
    isoCode: 'VA',
    numericIsoCode: 336,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'VE',
    name: 'Venezuela',
    isoCode: 'VE',
    numericIsoCode: 862,
    isPrimary: false,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    isPrimary: false,
    code: 'VN',
    name: 'Vietnam',
    isoCode: 'VN',
    numericIsoCode: 704,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'ZA',
    name: 'Südafrika',
    isoCode: 'ZA',
    numericIsoCode: 710,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    isPrimary: false,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'ZM',
    name: 'Sambia',
    isoCode: 'ZM',
    isPrimary: false,
    numericIsoCode: 894,
    addressFormat: CountryCodeAddressFormat.city_postCode,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    showState: false,
  ),
  CountryCode(
    meta: DataMeta.initial(),
    code: 'ZW',
    name: 'Simbabwe',
    isoCode: 'ZW',
    numericIsoCode: 716,
    addressFormat: CountryCodeAddressFormat.postCode_city,
    contactAddressFormat: CountryCodeContactAddressFormat.afterCompanyName,
    isPrimary: false,
    showState: false,
  ),
];
