include: package:elbdesk_lints/analysis_options.yaml

analyzer:
  exclude:
    - build/**,
    - "**/**.freezed.dart"
    - "**/**.g.dart"
    - lib/l10n/**

 

  errors:
    invalid_annotation_target: ignore
    undefined_prefixed_name: ignore

linter:
  rules:
    