arb-dir: lib/l10n
template-arb-file: elb_core_l10n_de.arb
output-localization-file: elb_core_localizations.dart
output-class: ElbCoreLocalizations
output-dir: lib/l10n
untranslated-messages-file: untranslated_messages.txt

synthetic-package: false
