arb-dir: lib/l10n
template-arb-file: elb_project_l10n_en.arb
output-localization-file: elb_project_localizations.dart
output-class: ElbProjectLocalizations
synthetic-package: false
output-dir: lib/l10n
nullable-getter: false