# This is the configuration file for your test environment. The test
# environment is meant to resemble the production environment as much as
# possible and may connect to production databases services and data. You use it
# for final test before deploying the production server.
#
# Typically, you will want to route the traffic through a load balancer
# which adds SSL security through https. If you use Serverpod's standard
# Terraform scripts to deploy your server, all you need to change in
# this file is the examplepod.com domain name.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: test.api.coe.elbdesk.cloud
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: test.insights.coe.elbdesk.cloud
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: test.web.coe.elbdesk.cloud
  publicPort: 443
  publicScheme: https

# This is the database setup for your servers. The default for the Google Cloud
# Engine Terraform configuration is to connect on a private IP address.
# If you are connecting on a public IP (e.g. on AWS or Google Cloud Run), you
# connect on the public IP of the database e.g. database-test.examplepod.com.
database:
  host: coe_elbdesk_cloud-test-postgres
  port: 5432
  name: coe_test
  user: postgres_test
  requireSsl: false

# This is the setup for Redis. The default for the Google Cloud Engine Terraform
# configuration is to connect on a private IP address.
# If you are connecting on a public IP (e.g. on AWS or Google Cloud Run), you
# connect on the public IP of the database e.g. redis-test.examplepod.com.
redis:
  enabled: false
  host: redis.private-test.elbdesk.cloud
  port: 6379
