arb-dir: lib/l10n
template-arb-file: elb_wm_l10n_de.arb
output-localization-file: elb_wm_localizations.dart
output-class: ElbWmLocalizations
synthetic-package: false
output-dir: lib/l10n
nullable-getter: false