FROM --platform=linux/amd64 ghcr.io/${GITHUB_REPOSITORY_OWNER}/flutter:${FLUTTER_VERSION}

ARG SERVERPOD_VERSION
ENV SERVERPOD_VERSION=${SERVERPOD_VERSION}

ARG FLUTTER_VERSION
ENV FLUTTER_VERSION=${FLUTTER_VERSION}

RUN dart pub global activate serverpod_cli ${SERVERPOD_VERSION}

