name: Build and Push ElbDesk Build Image

on:
  workflow_dispatch:
    inputs:
      serverpod_version:
        description: "Serverpod version to build"
        required: true
        default: "2.9.1"
        type: string
      flutter_version:
        description: "Flutter version to build"
        required: true
        default: "3.32.5"
        type: string
      version_bump:
        description: "Version to bump (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the current version
        id: version
        run: |
          # Try to get the latest version tag
          CURRENT_VERSION=$(docker run --rm ghcr.io/${{ github.repository_owner }}/elbdesk-build:latest -v 2>/dev/null || echo "0.0.0")

          # Parse version components
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)

          # Increment version based on input
          case "${{ inputs.version_bump }}" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: .docker/elbdesk-build.Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/app-ahoi/elbdesk-build:latest
            ghcr.io/app-ahoi/elbdesk-build:${{ steps.version.outputs.new_version }}
          build-args: |
            SERVERPOD_VERSION=${{ inputs.serverpod_version }}
            FLUTTER_VERSION=${{ inputs.flutter_version }}
