name: Build and Push Flutter Container Image to GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Flutter version to build'
        required: true
        default: '3.32.5'
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Flutter version to build'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            FLUTTER_VERSION=${{ inputs.version }}
          context: .
          file: ./.docker/flutter.Dockerfile
          push: true
          tags: ghcr.io/app-ahoi/flutter:${{ inputs.version }}