name: Build and push Serverpod server Docker image

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      GHCR_ORG:
        required: true
        type: string
      OWNER:
        required: true
        type: string
      SERVERPOD_SERVER:
        required: true
        type: string
      SHOULD_RUN_JOB:
        required: true
        type: boolean
    secrets:
      EMAIL:
        required: true
      DATABASE_PASSWORD:
        required: true
      SERVERPOD_PASSWORDS:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

jobs:
  build-and-push-image:
    if: inputs.SHOULD_RUN_JOB
    name: Build and push Serverpod server Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ${{ fromJson(inputs.SERVERPOD_SERVER).PATH }}
    steps:
      - name: Get token from Github App
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # owner is required, otherwise the creds will fail the checkout step
          owner: ${{ inputs.OWNER }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Create passwords file
        working-directory: ${{ fromJson(inputs.SERVERPOD_SERVER).PATH }}
        shell: bash
        env:
          SERVERPOD_PASSWORDS: ${{ secrets.SERVERPOD_PASSWORDS }}
        run: |
          pwd
          ls -la
          echo "$SERVERPOD_PASSWORDS" > config/passwords.yaml
          ls config/

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push serverpod Docker image
        uses: docker/build-push-action@v5
        with:
          # context: ./${{ fromJson(inputs.SERVERPOD_SERVER).PATH }}
          context: .
          file: ./${{ fromJson(inputs.SERVERPOD_SERVER).PATH }}/serverpod.Dockerfile
          push: true
          tags: ghcr.io/${{ inputs.GHCR_ORG }}/${{ fromJson(inputs.SERVERPOD_SERVER).NAME }}_${{ fromJson(inputs.SERVERPOD_SERVER).RUN_MODE }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8
          build-args: |
            GITHUB_TOKEN=${{ steps.app_token.outputs.token }}
            GITHUB_USER=${{ github.actor }}
            SERVERPOD_RUN_MODE=${{ fromJson(inputs.SERVERPOD_SERVER).RUN_MODE }}