name: Build and Push Serverpod Base Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Serverpod version to build'
        required: true
        default: '1.2.5'
        type: string
      flutter_version:
        description: 'Flutter version to build'
        required: true
        default: '3.24.3'
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Serverpod version to build'
        required: true
        type: string
      flutter_version:
        description: 'Flutter version to build'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            SERVERPOD_VERSION=${{ inputs.version }}
            FLUTTER_VERSION=${{ inputs.flutter_version }}
          context: .
          file: serverpod.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/serverpod:${{ inputs.version }}