name: Test Migrations for Production

on:
  pull_request:
    branches: [production]
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  packages: write

jobs:
  test-migrations:
    uses: ./.github/workflows/test-migrations-jobs.yml
    with:
      NAME: "coe_elbdesk_cloud"
      PATH: "servers/elbdesk_server"
      RUN_MODE: "production"
      DATABASE_NAME: "postgres_test_database"
      DATABASE_USER: "postgres_test_user"
      DATABASE_PORT: "5432:5432"
      OWNER: ${{ github.repository_owner }}
      SERVERPOD_VERSION: "2.9.1"
      FLUTTER_VERSION: "3.32.5"
    secrets:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD_PRODUCTION }}
      SERVERPOD_PASSWORDS: ${{ secrets.SERVERPOD_PASSWORDS }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
