import 'package:elbdesk_core/elbdesk_core.dart';
import 'package:elbdesk_crm/src/language_code/models/language_code.dart';

final List<LanguageCode> allLanguageCodesForSetup = [
  LanguageCode(
    isPrimary: false,
    code: 'BGR',
    name: 'Bulgarisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'CHS',
    name: 'Vereinfachtes Chinesisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'CSY',
    name: 'Tschechisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'DAN',
    name: 'Dänisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'DEA',
    name: 'Deutsch (Österreich)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'DES',
    name: 'Deutsch (Schweiz)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'DEU',
    name: 'Deutsch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ELL',
    name: 'Griechisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ENA',
    name: 'Englisch (Australien)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ENC',
    name: 'Englisch (Kanada)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ENG',
    name: 'Englisch (Großbritannien)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ENI',
    name: 'Englisch (Irland)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ENP',
    name: 'Englisch (Philippinen)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ENU',
    name: 'Englisch (USA)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ENZ',
    name: 'Englisch (Neuseeland)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ESM',
    name: 'Spanisch (Mexiko)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ESN',
    name: 'Spanisch (Spanien)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ESO',
    name: 'Spanisch (Kolumbien)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ESP',
    name: 'Spanisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ESR',
    name: 'Spanisch (Peru)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ESS',
    name: 'Spanisch (Argentinien)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ETI',
    name: 'Estnisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'FIN',
    name: 'Finnisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'FRA',
    name: 'Französisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'FRB',
    name: 'Französisch (Belgien)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'FRC',
    name: 'Französisch (Kanada)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'FRS',
    name: 'Französisch (Schweiz)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'HRV',
    name: 'Kroatisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'HUN',
    name: 'Ungarisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'IND',
    name: 'Indonesisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ISL',
    name: 'Isländisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ITA',
    name: 'Italienisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ITS',
    name: 'Italienisch (Schweiz)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'JPN',
    name: 'Japanisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'KOR',
    name: 'Koreanisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'LTH',
    name: 'Litauisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'LVI',
    name: 'Lettisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'MSL',
    name: 'Malaiisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'NLB',
    name: 'Niederländisch (Belgien)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'NLD',
    name: 'Niederländisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'NON',
    name: 'Norwegisch (Nynorsk)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'NOR',
    name: 'Norwegisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'PLK',
    name: 'Polnisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'PTB',
    name: 'Portugiesisch (Brasilien)',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'PTG',
    name: 'Portugiesisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'ROM',
    name: 'Rumänisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'RUS',
    name: 'Russisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'SKY',
    name: 'Slowakisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'SLV',
    name: 'Slowenisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'SRP',
    name: 'Serbisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'SVE',
    name: 'Schwedisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'THA',
    name: 'Thai',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'TRK',
    name: 'Türkisch',
    meta: DataMeta.initial(),
  ),
  LanguageCode(
    isPrimary: false,
    code: 'UKR',
    name: 'Ukrainisch',
    meta: DataMeta.initial(),
  ),
];
